---
abstract: 'Pictogram entities filter'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sledge-Plugin-PictogramEntities
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Entities::ConvertPictogramMobileJp: 0.06
  HTTP::MobileAgent: 0.27
  perl: 5.8.0
version: 0.03
